/*!
 * reveal.js Zoom plugin
 */
const Plugin={id:"zoom",init:function(e){e.getRevealElement().addEventListener("mousedown",function(t){var n=/Linux/.test(window.navigator.platform)?"ctrl":"alt",o=(e.getConfig().zoomKey?e.getConfig().zoomKey:n)+"Key",i=e.getConfig().zoomLevel?e.getConfig().zoomLevel:2;t[o]&&!e.isOverview()&&(t.preventDefault(),zoom.to({x:t.clientX,y:t.clientY,scale:i,pan:!1}))})},destroy:()=>{zoom.reset()}};export default()=>Plugin;
/*!
 * zoom.js 0.3 (modified for use with reveal.js)
 * http://lab.hakim.se/zoom-js
 * MIT licensed
 *
 * Copyright (C) 2011-2014 Hakim El Hattab, http://hakim.se
 */var zoom=function(){function e(e,t){var i=n();if(e.width=e.width||1,e.height=e.height||1,e.x-=(window.innerWidth-e.width*t)/2,e.y-=(window.innerHeight-e.height*t)/2,c)if(1===t)document.body.style.transform="";else{var d=i.x+"px "+i.y+"px",l="translate("+-e.x+"px,"+-e.y+"px) scale("+t+")";document.body.style.transformOrigin=d,document.body.style.transform=l}else 1===t?(document.body.style.position="",document.body.style.left="",document.body.style.top="",document.body.style.width="",document.body.style.height="",document.body.style.zoom=""):(document.body.style.position="relative",document.body.style.left=-(i.x+e.x)/t+"px",document.body.style.top=-(i.y+e.y)/t+"px",document.body.style.width=100*t+"%",document.body.style.height=100*t+"%",document.body.style.zoom=t);o=t,document.documentElement.classList&&(1!==o?document.documentElement.classList.add("zoomed"):document.documentElement.classList.remove("zoomed"))}function t(){var e=.12,t=window.innerWidth*e,l=window.innerHeight*e,s=n();d<l?window.scroll(s.x,s.y-14/o*(1-d/l)):d>window.innerHeight-l&&window.scroll(s.x,s.y+(1-(window.innerHeight-d)/l)*(14/o)),i<t?window.scroll(s.x-14/o*(1-i/t),s.y):i>window.innerWidth-t&&window.scroll(s.x+(1-(window.innerWidth-i)/t)*(14/o),s.y)}function n(){return{x:window.scrollX!==undefined?window.scrollX:window.pageXOffset,y:window.scrollY!==undefined?window.scrollY:window.pageYOffset}}var o=1,i=0,d=0,l=-1,s=-1,c="transform"in document.body.style;return c&&(document.body.style.transition="transform 0.8s ease"),document.addEventListener("keyup",function(e){1!==o&&27===e.keyCode&&zoom.out()}),document.addEventListener("mousemove",function(e){1!==o&&(i=e.clientX,d=e.clientY)}),{to:function(n){if(1!==o)zoom.out();else{if(n.x=n.x||0,n.y=n.y||0,n.element){var i=20,d=n.element.getBoundingClientRect();n.x=d.left-i,n.y=d.top-i,n.width=d.width+2*i,n.height=d.height+2*i}n.width!==undefined&&n.height!==undefined&&(n.scale=Math.max(Math.min(window.innerWidth/n.width,window.innerHeight/n.height),1)),n.scale>1&&(n.x*=n.scale,n.y*=n.scale,e(n,n.scale),!1!==n.pan&&(l=setTimeout(function(){s=setInterval(t,1e3/60)},800)))}},out:function(){clearTimeout(l),clearInterval(s),e({x:0,y:0},1),o=1},magnify:function(e){this.to(e)},reset:function(){this.out()},zoomLevel:function(){return o}}}();